import groovy.json.JsonSlurper

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'tk.mapcollector'
    compileSdk = 37

    defaultConfig {
        def inputFile = rootProject.file("../package.json")
        def packageJson = new JsonSlurper().parseText(inputFile.text)

        applicationId "tk.mapcollector"
        minSdk 26
        targetSdk 37
        versionCode packageJson.androidVersion
        versionName packageJson.version

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    packagingOptions {
        resources.excludes.add("META-INF/*")
    }
    kotlin {
        jvmToolchain(11)
    }

    // Makes sure that BuildConfig is available, otherwise there will be very strange errors,
    // see https://stackoverflow.com/a/76124393/4284627
    android.buildFeatures.buildConfig = true
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.webkit
    implementation libs.commons.io
    implementation libs.commons.text
    implementation libs.activity.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidsvg.aar
    implementation libs.activity.ktx
    implementation libs.httpclient
    implementation libs.ktor.client.core
    implementation libs.ktor.client.android
    implementation libs.kotlinx.coroutines
    implementation libs.androidsuspendutils
}

tasks.register('jslibs', Copy) {
    def libsFolder = "src/main/assets/libs"

    delete libsFolder
    project.mkdir libsFolder

    def lodashFile = file("${libsFolder}/+esm")
    new URL("https://cdn.jsdelivr.net/npm/lodash@4.17.21/+esm").withInputStream { i -> lodashFile.withOutputStream { it << i } }

    from "../../node_modules/@flatten-js/core/dist/main.mjs"
    from "../../node_modules/@popperjs/core/dist/umd/popper.min.js"
    from "../../node_modules/i18next/dist/esm/i18next.js"
    from "../../node_modules/peerjs/dist/peerjs.min.js"
    from "../../node_modules/svg-pan-zoom/dist/svg-pan-zoom.min.js"
    from "../../node_modules/tippy.js/dist/tippy-bundle.umd.min.js"
    into libsFolder
}

gradle.projectsEvaluated {
    mergeDebugAssets.dependsOn jslibs
    mergeReleaseAssets.dependsOn jslibs
    tasks.findByName("lintVitalAnalyzeDebug")?.dependsOn jslibs
    tasks.findByName("lintVitalAnalyzeRelease")?.dependsOn jslibs
    tasks.findByName("generateDebugLintVitalReportModel")?.dependsOn jslibs
    tasks.findByName("generateReleaseLintVitalReportModel")?.dependsOn jslibs
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}